### ISSUE TITLE
All prefabs end up white until manually selecting the object and opening the dropdown

### ISSUE THREAD

**Issue by MostHated** [Roland09/BetterLitShaderExtensions#2]
Hey there,
    I am not really sure if this is due to the tools conversion, or something with the shader itself, but as you will see below, most all prefabs were just a white texture after I converted them until I click on it, go to the shader and open the dropdown. I tried reimporting the prefabs, the materials, etc, just to see if that would help, but unfortunately, it did not. I still have to go to each one and open that dropdown. Is there any sort of additional step that might be able to be added to the tools process which could possibly handle this automatically?

(It's a bit too large of a file video clip to embed, it seems)
https://i.imgur.com/7ga9lEO.gifv

Thanks,
-MH

**Comment by Roland09** [comment]
Thanks for reporting this. Fixed it.

BetterLit Shaders does automatic assignment of textures when you click on a material. However since multiple materials are converted, only the one with the focus is visually assigned the textures, the rest remain white until you click on the material. You'd have to click through all of the other ones. Now the assignment is done in the converter.
